apiVersion: v1
kind: Service
metadata:
  name: tomcatsrv
  labels:
    name: tomcatsrv
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: tomcat
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  tomcat-deploy
  labels:
    name:  tomcat
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  tomcat
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: tomcat
        name:  tomcat-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        command: ["/bin/sh","-c","wget -O /usr/local/tomcat/webapps/webpoc.war https://github.com/msaravindh/akspoc/raw/master/webpoc.war && catalina.sh run"]
        env:
        - name: MYSQL_URI
          value: "jdbc:mysql://mysqlhyd.mysql.database.azure.com:3306/employee_db?useSSL=true&requireSSL=false&serverTimezone=UTC"
        - name: MYSQL_USER
          value: "mysqlroot@mysqlhyd"
        ports:
        - containerPort:  8080
          name:  tomcat
        imagePullPolicy: Always
      restartPolicy: Always
